### ISSUE TITLE
DNS Tunneling and ICMP Tunneling

### ISSUE THREAD

**Issue by ThrDev** [kylemcdonald/FreeWifi#4]
You should mention both DNS Tunneling and ICMP Tunneling as mostly-reliable ways of accessing the internet through portal-locked wireless access point.

http://code.kryo.se/iodine/
https://github.com/DhavalKapil/icmptunnel

Obviously these are for more advanced users, but they are also good ways of accessing the internet for completely free at most places.

**Comment by kylemcdonald** [comment]
Thanks! I've heard about both of these but haven't used them personally. Have you? If so, on which networks (or, what kind of networks, if you don't want to implicate yourself) have you found them to be useful? I've also heard they can both be very slow, has that been your experience?

If you would like to submit a PR with an additional sentence or two and some links I would appreciate it!
