### ISSUE TITLE
On a mac, received this error

### ISSUE THREAD

**Issue by youthfulguru** [kylemcdonald/FreeWifi#9]
When I typed $ cd FreeWifi && sudo pip install -r requirements.txt

I got this error:
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-eB0BuK/wireless/

**Comment by atbj505** [comment]
i got same error on MAC

**Comment by atbj505** [comment]
I got same error on MAC

**Comment by kylemcdonald** [comment]
http://stackoverflow.com/questions/35991403/python-pip-install-gives-command-python-setup-py-egg-info-failed-with-error-c

```
Error code 1 is defined in errno.h and means Operation not permitted
```

Maybe try running `pip install -r requirements.txt ` without `sudo`? This might be related to having multiple versions of python running on your system.

Also try installing `wireless` directly: `pip install wireless`. If this doesn't work, it's a problem with `wireless` and you should add an issue in [that repo](https://github.com/joshvillbrandt/wireless/issues). Either way, I'm pretty sure this is a Python configuration issue, not a problem with this repo.

Hope that's helpful!

**Comment by youthfulguru** [comment]
Tried the operation without sudo, got the following message:
error: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/netifaces.so'

Tried pip install wireless and received this message:
error: could not create '/Library/Python/2.7/site-packages/wireless': Permission denied
